### ISSUE TITLE
Investigate using Electron Global objects in lieu of large-data IPC and data merging

### ISSUE THREAD

**Issue by AABoyles** [CDCgov/MicrobeTrace-Archive#132]
The session object in any given view can be a little bit large. I just looked at bulgaria in the network view: 23MB! That's a lot to be pushing through IPC. Maybe we should use globals instead?

See: https://webcache.googleusercontent.com/search?q=cache:mEaLq0LtPOAJ:https://discuss.atom.io/t/how-to-set-global-variable-of-main-process/24833+&cd=1&hl=en&ct=clnk&gl=us and https://github.com/electron/electron/issues/1258

**Comment by p3nGu1nZz** [comment]
i just did some research into this topic and updated my findings in https://github.com/electron/electron/issues/1258

**Comment by AABoyles** [comment]
Hey @1-14x0r ! Your comment is awesome, thanks for doing that research!

**Comment by AABoyles** [comment]
Based on my reading of @1-14x0r's conclusions, getGlobal is little more than a wrapper for sendSync, meaning swapping between them shouldn't save us any time. The slow part turns out to be serialization, which we can mitigate by sending transformation _instructions_, rather than complete datasets. Serializing an int is a lot faster than serializing a 23MB Object.

The downside of this is the risk of errors when the system gets out-of-sync. Unfortunately, I need to solve this problem now, and deal with that problem when it crops up. :man_shrugging:

**Comment by p3nGu1nZz** [comment]
I would suggest creating a DataStoreManager in your main process that wraps your collections (such as NeDB, MongoDB, or some type of SQL db). Within this class, have various static functions that you can call from your renderer process via electron.remote. Have the static functions dispatch various async events corresponding to query, update, insert, delete, etc..

Then in your DataStoreManager create listeners for these event with the actual code to execute on your collections. This is also where you want to serialize the objects with JSON.stringify() (or with another serialize algorithm such as https://github.com/fastify/fast-json-stringify). 

From where you called the remote static function in your renderer class, create a listener for this async event. Then deserialize it, and save it in your renderer where you need it. Just be careful with having multiple listeners on the same event channel. Meaning, I wouldn't try to use the same event channels for multiple data collections.

This will create a lot of event channels, however this does not impact the speed of sending data over IPC (named pipes). The key is to make unique channel names for each collection and make sure you send these events async. 

Your data wont get out of sync doing it this way, since you are getting a new collection in the gui when you do a query. Just make sure you do not modify the collections in the renderer directly. Make sure you use the remote.DataStoreManager, and you should be good.

Anyways hope that provides you with some useful information on how we have done this before.
