### ISSUE TITLE
Some options disappear when the input is an edge list.

### ISSUE THREAD

**Issue by nrf1** [CDCgov/MicrobeTrace-Archive#9]
If I input an edge list, I lose several options. In the settings, under Links, the pruning and threshold options go away, so I can’t filter. Also, the sequences tab goes away, which makes sense, but since it seems like I can upload trees and sequences separately through that viewer, it could be useful to still have that as an option.

**Comment by AABoyles** [comment]
This disappearing act is intentional. Currently, MicrobeTrace only supports filtering on genetic distances that it calculates, which means that it needs sequences, and it only recognizes sequences if it parses them from a FASTA file (in contrast to, say, downloading a CSV with a sequence field from [LANL](https://www.hiv.lanl.gov/components/sequence/HIV/search/search.html)). Current development plans call for more flexibility on this front (identifying sequences in CSVs, filtering on arbitrary fields in Edge lists, etc.) but is not currently high-priority.

As for the sequence viewer, I'll discuss the feature and reply again.

**Comment by AABoyles** [comment]
OK, so I've enabled the sequence Viewer (b7cd0fd9454eee10c8e1a71510c2ae222c48e339) even for situations in which we don't actually have sequences so the Phylogenetic Tree Viewer should still be accessible.

As for filtering on data values which aren't the TN93s that MicrobeTrace computes itself, that's a work in progress (mostly 7d47efcb9c2eb215d919bd8a4e0fc2fee9d2f67e, but also a26637b2632dc7c762eeec237c7a2f8ede55156f and 8b90ba19f6589aa80c0b9099cfa693cad1b2cae2)

**Comment by AABoyles** [comment]
Fixed by b5a22ad2ed7af508fb38a6bb1a897c9340c47fd0
